version: '3.4'
services:
  odas_backend:
    container_name: odas_flask_t
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: []
    ports:
      - "5000:1000" # external:internal
    volumes:
      - ./backend:/odas
  redis:
    image: "redis:alpine"
    container_name: db_t
    ports:
    - 6379:6379
  odas_frontend:
    container_name: odas_vue_t
    restart: always
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: # uncomment selected stage: auto-reloading dev OR hosted by nginx for release    
              dev-stage
              #production-stage 
    command: []
    ports:
      - "8081:80" # external:internal
    volumes:
      - "./frontend/vueapp/src:/app/src"
    environment:
      - ENV=development
      - PORT=80 #need to be 80, becouse of nginx