version: '2'
services:
  odas:
    container_name: odas_c
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "5000:1000" # external:internal
    volumes:
      - .:/odas
  redis:
    image: "redis:alpine"
    container_name: "db"
    ports:
    - 6379:6379